= Sample Application image:https://travis-ci.org/oasp/oasp4js.svg?branch=development["Build Status",link="https://travis-ci.org/oasp/oasp4js"] image:https://coveralls.io/repos/oasp/oasp4js/badge.svg?branch=development["Coverage Status",link="https://coveralls.io/r/oasp/oasp4js?branch=development"]
The sample application is built on top of the https://github.com/oasp/oasp4js-app-template[application template] and is an AngularJS application. Some of the AngularJS modules (e.g. oasp-security, oasp-i18n, etc.) which can be reused in your application are available in https://github.com/oasp/oasp4js-bower[this repository] either directly or using the Bower package manager. The sample application needs the https://github.com/oasp/oasp4j[oasp4j] (Java) server part to be installed.

== Getting Started

To get started you need to clone both the `oasp4j` and `oasp4js` repositories containing the server and the client part respectively. Each of them is to be built and started to talk to each other it. There are two ways to get the sample application working: eithter by getting the https://github.com/elyamad/oasp[oasp IDE] and running it from there or setting up the IDE manually. 

= Full oasp IDE installation

Note : $projectLoc is your path C:\projects\oasp

If you want to install full OASP IDE and get both server and client code please follow steps described in https://github.com/oasp/oasp4j/wiki/oasp-ide-setup[oasp IDE setup]. The `oasp IDE` already contains software (Node.js, Gulp, Bower, Maven) required to run the sample application; only Git has to be additionally installed. 

= IDE Setup

1. Open console.bat and check out the git repositories you need to work on into $projectLoc\workspaces\main. with the following commands:

....
cd workspaces/main
git clone --recursive https://github.com/oasp/oasp4j.git
git clone https://github.com/oasp/oasp4js.git
....


2. Run the script $projectLoc\update-all-workspaces.bat.

3. Run the script $projectLoc\eclipse-main.bat to start the Eclipse IDE.

4. In Eclipse select File > Import > Maven > and Import existing Maven Project and then choose the cloned projects from your workspace. Root Directory: $projectLoc\workspaces\main. You can also click the Browse button and select the folder structure. (If there is a exception: Auto share git projects (Waiting) - choose Run in Background)

5. Execute the application by starting the ´io.oasp.gastronomy.restaurant.SpringBootApp´. Select the class and click the right mouse button. In the context menu select the entry 'Run as ⇒ Java Application' (or 'Debug as …​'). The application starts up and creates log entries in the Eclipse Console Tab. Once started, the OASP server applications runs on http://localhost:8081 with /oasp4j-sample-server/ as context-root. Access Server on base url: http://localhost:8081/oasp4j-sample-server, login with waiter/waiter and have a look at the services list provided.

6. If you want to properly test the example application you might want to build the OASP4js-client as follows:

 ** Run console.bat.

 ** Now call the following commands:

....
cd workspaces/main/oasp4js/
npm install -g gulp
npm install -g bower
npm install
cd java
mvn install
....

If [INFO] BUILD SUCCESS → next step

 ** You can then extract the client from oasp4js/java/target/oasp4js-sample-*-web.zip into oasp4j/oasp4j-samples/oaps4j-sample-server/src/main/webapp/jsclient. You may have to create the folder jsclient by yourself. Restart your tomcat and open http://localhost:8081/oasp4j-sample-server/ or for simpler development run both tomcat and a grunt-server as overlay via:

....
cd workspaces/main/oasp4js
gulp serve
....

A new tab in your webbrowser should open and you can try to sign in.

Test - User Name: waiter, Password: waiter. (Exception: If "Authentication failed. Please try again!" → try to restart Tomcat in Eclipse or try to click the right button on Tomcat → Clean…​ or Clean Tomcat Work Directory)





